<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOCnDS39\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOCnDS39/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerOCnDS39.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerOCnDS39\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerOCnDS39\srcApp_KernelProdContainer([
    'container.build_hash' => 'OCnDS39',
    'container.build_id' => '828b6aea',
    'container.build_time' => 1565001611,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOCnDS39');
