<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3KHrLT7\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3KHrLT7/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3KHrLT7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3KHrLT7\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container3KHrLT7\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '3KHrLT7',
    'container.build_id' => '1dd066bd',
    'container.build_time' => 1565173623,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3KHrLT7');
